// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CartPageController from "./cart_page_controller"
application.register("cart-page", CartPageController)

import CheckoutPaymentController from "./checkout_payment_controller"
application.register("checkout-payment", CheckoutPaymentController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocaleSelectorController from "./locale_selector_controller"
application.register("locale-selector", LocaleSelectorController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ThemeSwitcherController from "./theme_switcher_controller"
application.register("theme-switcher", ThemeSwitcherController)

import TopBarController from "./top_bar_controller"
application.register("top-bar", TopBarController)
